# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
sudo: required

addons:
  postgresql: '9.5'
  apt:
    packages:
      - libsqlite3-dev
      - libpq-dev

services:
  - docker
  - mysql

env:
  global:
    - CRATE_NAME=dytp

matrix:
  include:
    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=mips-unknown-linux-gnu
    - env: TARGET=mips64-unknown-linux-gnuabi64
    - env: TARGET=mips64el-unknown-linux-gnuabi64
    - env: TARGET=mipsel-unknown-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu
    - env: TARGET=powerpc64-unknown-linux-gnu
    - env: TARGET=powerpc64le-unknown-linux-gnu
    - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # *BSD
    - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
    - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

before_install:
  - set -e
  - rustup self update
  - sudo apt-cache search libpq-dev
  - echo $LD_LIBRARY_PATH
  - which psql
  - export ${LD_LIBRARY_PATH}:/usr/lib/postgresql/9.5/lib

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: "mXR1TvFAlNKLuykM2eWsygVR92OP7uCPp4kZyt32ZhMrFu1PwM2wS/R3T+soDgsSwan6iFd66YnlN4U1jx9bxVnq92zLR4jYSgsMhmk1POcPG9dTvHRozuIC8A7CesNtzsxovhP3JNjLr+teqVEfm2qAZalDn0RMWCDid9FEarBvteuUax/A7FjKDl48TY69GKSfqYP7DoePyordDA6ObW9RyibsIGz93dQB+Xk4LcVON3pLNn4aNwm1V0tNN48XMMF76Y48Gj6ypA7qsp0H8elufufcKLF7YGOT5U3hfWzvpRNqWsDrvm2zbwvouVPjuDWPjp7t8nSIcL2t26UkiVFDFQczJK7ofCs0FivKfZdnso1OsSEFPLHroNmzkFf0j3qnT/VDBCXnx/uzAfL8/pIDk34tFZ87RSy4B11XVx8bGScWqIyqV4+XgzQBfy5DoSLeGsoWFgXdPVmhNwFJlADNma4ZwTAIkppsmi5TS6eXPnMv5+TMPPl8QFSUgV+Z4/pHvd/XXWvfgGdCdlET2hvL0gLbncRAZiWkHtFc1a3gXd4Aaho6MKP/YdRuPTV/Paot0ZKIylDgKpH3GAtKMUw40SDBwK2yz7XPWzM0M/5fWg/HSU98mNpYM0WzfzmuyHy/d3NfDX0wuIm0b+kAz8ekg1QiciASeMSp0x6jRpY="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
