# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

services:
  - postgresql95

environment:
  global:
    RUST_VERSION: stable
    CRATE_NAME: dytp

  matrix:
    - TARGET: i686-pc-windows-gnu
    - TARGET: x86_64-pc-windows-gnu

install:
  - ps: >-
      If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw32\bin'
      }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build --target %TARGET% --features all &&
      cargo build --target %TARGET% --features all --release &&
      cargo test --target %TARGET% --features all &&
      cargo test --target %TARGET% --features all --release
    )

before_test:
  - SET PATH=C:\Program Files\PostgreSQL\9.5\bin;%PATH%

before_deploy:
  - cargo rustc --target %TARGET% --features all --release --bin dytp -- -C lto
  - ps: ci\before_deploy.ps1

deploy:
  artifact: /.*\.zip/
  auth_token:
    secure: 10cuGdUjuqR0WoGow1rItdM8rsUKUFK7lPQKV15Yof+rImG2jZzlu5phcDV8rZQq
  description: ''
  on:
    RUST_VERSION: stable
    appveyor_repo_tag: true
  provider: GitHub

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  - provider: Email
    on_build_success: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
